[package]
name = "tldr"
version = "0.1.1"
authors = ["Rizky Luthfianto <mrluthfianto@gmail.com>"]
description = "Rust client for tldr. tldr is a simplified and community-driven man pages"
license = "MIT"

[dependencies]
hyper = '>= 0.7.1'
ansi_term = ">= 0.7"